-- Baseline schema for StreamLine.
--
-- Mirrors the ChatMessage entity exactly, because the application runs with
-- spring.jpa.hibernate.ddl-auto=validate: Hibernate checks this schema at
-- startup and refuses to boot if the two have drifted, instead of silently
-- altering tables the way ddl-auto=update did.
CREATE TABLE messages (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id      INTEGER NOT NULL,
    username     VARCHAR(20) NOT NULL,
    message      VARCHAR(500) NOT NULL,
    timestamp    TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    message_type VARCHAR(10) NOT NULL,
    room_id      VARCHAR(64)
);

-- History replay filters by room and orders by timestamp.
CREATE INDEX idx_messages_room_timestamp ON messages (room_id, timestamp);

-- Author-scoped search would otherwise scan every row in the room.
CREATE INDEX idx_messages_room_username ON messages (room_id, username);
