-- Emoji reactions on stored messages.
--
-- A separate table rather than a column on messages: reactions are many per
-- message and are added and removed independently, so storing them inline would
-- mean rewriting the message row on every click.
CREATE TABLE message_reactions (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    message_id BIGINT NOT NULL,
    room_id    VARCHAR(64) NOT NULL,
    username   VARCHAR(20) NOT NULL,
    emoji      VARCHAR(16) NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,

    -- One person reacting twice with the same emoji is the same reaction, not
    -- two. The unique constraint makes a repeat click a no-op at the database
    -- rather than something every caller has to remember to check.
    CONSTRAINT uq_reaction_per_user UNIQUE (message_id, username, emoji),

    CONSTRAINT fk_reaction_message FOREIGN KEY (message_id)
        REFERENCES messages (id) ON DELETE CASCADE
);

-- Reactions are always read for a whole message at once.
CREATE INDEX idx_reactions_message ON message_reactions (message_id);

-- Scoped lookups and deletes go by room, as everywhere else in the API.
CREATE INDEX idx_reactions_room ON message_reactions (room_id);
